version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: npm
    directory: /desktop
    schedule:
      interval: monthly
    groups:
      desktop-dependencies:
        patterns: ["*"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
